import type { ClassicConfig } from '@typescript-eslint/utils/ts-eslint';

export = {
  plugins: ['@manbearwiz/eslint-plugin-rxjs'],
  rules: {
    '@manbearwiz/rxjs/finnish': 'off',
    '@manbearwiz/rxjs/no-async-subscribe': 'off',
    '@manbearwiz/rxjs/no-connectable': 'off',
    '@manbearwiz/rxjs/no-create': 'off',
    '@manbearwiz/rxjs/no-cyclic-action': 'off',
    '@manbearwiz/rxjs/no-exposed-subjects': 'off',
    '@manbearwiz/rxjs/no-finnish': 'off',
    '@manbearwiz/rxjs/no-ignored-error': 'off',
    '@manbearwiz/rxjs/no-ignored-notifier': 'off',
    '@manbearwiz/rxjs/no-ignored-observable': 'off',
    '@manbearwiz/rxjs/no-ignored-subscribe': 'off',
    '@manbearwiz/rxjs/no-ignored-subscriptions': 'off',
    '@manbearwiz/rxjs/no-implicit-any-catch': 'off',
    '@manbearwiz/rxjs/no-nested-subscribe': 'off',
    '@manbearwiz/rxjs/no-redundant-notify': 'off',
    '@manbearwiz/rxjs/no-subclass': 'off',
    '@manbearwiz/rxjs/no-subject-unsubscribe': 'off',
    '@manbearwiz/rxjs/no-subject-value': 'off',
    '@manbearwiz/rxjs/no-subscribe-handlers': 'off',
    '@manbearwiz/rxjs/no-topromise': 'off',
    '@manbearwiz/rxjs/no-unbound-methods': 'off',
    '@manbearwiz/rxjs/no-unsafe-catch': 'off',
    '@manbearwiz/rxjs/no-unsafe-first': 'off',
    '@manbearwiz/rxjs/no-unsafe-subject-next': 'off',
    '@manbearwiz/rxjs/no-unsafe-switchmap': 'off',
    '@manbearwiz/rxjs/no-unsafe-takeuntil': 'off',
    '@manbearwiz/rxjs/prefer-observer': 'off',
    '@manbearwiz/rxjs/suffix-subjects': 'off',
    '@manbearwiz/rxjs/throw-errors': 'off',
  },
} satisfies ClassicConfig.Config;
